### ISSUE TITLE
Parameter `nullable = true` override doesn't seem to work

### ISSUE THREAD

**Issue by gkoz** [gkoz/gir#176]
```toml
[[object]]
name = "Gtk.Entry"
status = "generate"
    [[object.function]]
    name = "set_placeholder_text"
        [[object.function.parameter]]
        name = "text"
        nullable = true
```
Expected outcome:
```rust
fn set_placeholder_text(&self, text: Option<&str>);
```
